debug: true

spring:
  application:
    name: cambunda
  profiles:
    active: local
  docker:
    compose:
      enabled: false
  devtools:
    add-properties: false

camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      broker:
        gateway-address: localhost:26500
      base-url: http://localhost
    auth:
      type: none
    prefer-rest-over-grpc: false

  process:
    id: Contract_Validation

tasklist:
  client:
    profile: simple
    enabled: true
    base-url: http://localhost:8082
    session-timeout: PT10M
    username: demo
    password: demo

  multi-tenancy:
    enabled: true

  identity:
    userAccessRestrictionsEnabled: false
    resourcePermissionsEnabled: true

  zeebe:
    gatewayAddress: localhost:26500

  elasticsearch:
    clusterName: elasticsearch
    url: http://localhost:9200

  zeebeElasticsearch:
    clusterName: elasticsearch
    url: http://localhost:9200
    prefix: zeebe-record

quarkus:
  langchain4j:
    openai:
      api-key: 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