debug: true

spring:
  application:
    name: cambunda
  profiles:
    active: local
  docker:
    compose:
      enabled: false
  devtools:
    add-properties: false
  ai:
    chat:
      options:
        model: gpt-4o

camunda:
  client:
    mode: self-managed
    zeebe:
      enabled: true
      broker:
        gateway-address: localhost:26500
      base-url: http://localhost
    auth:
      type: none
    prefer-rest-over-grpc: false

  process:
    id: Contract_Validation

tasklist:
  client:
    profile: simple
    enabled: true
    base-url: http://localhost:8082
    session-timeout: PT10M
    username: demo
    password: demo

  multi-tenancy:
    enabled: true

  identity:
    userAccessRestrictionsEnabled: false
    resourcePermissionsEnabled: true

  zeebe:
    gatewayAddress: localhost:26500

  elasticsearch:
    clusterName: elasticsearch
    url: http://localhost:9200

  zeebeElasticsearch:
    clusterName: elasticsearch
    url: http://localhost:9200
    prefix: zeebe-record

quarkus:
  langchain4j:
    openai:
      chat-model:
        model-name: gpt-4o
        log-requests: true
        log-responses: true
    timeout: 1m